### ISSUE TITLE
Failed to activate the git-gui package

### ISSUE THREAD

**Issue by Golpesar0321** [andrewrynhard/atom-git-gui#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [git-gui](https://github.com/andrewrynhard/atom-git-gui) package 0.1.27

### Stack Trace

Failed to activate the git-gui package

```
At watch /home/mahmoud/Desktop/.git ENOENT

Error: watch /home/mahmoud/Desktop/.git ENOENT
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at GitGuiConfigView.initialize (/packages/git-gui/lib/git-gui-config-view.coffee:23:25)
    at /packages/git-gui/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/git-gui/lib/git-gui-config-view.coffee:9:7)
    at Object.content (/packages/git-gui/lib/git-gui-view.coffee:24:44)
    at Builder.tag (/packages/git-gui/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/git-gui/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/git-gui/lib/git-gui-view.coffee:23:10)
    at Builder.tag (/packages/git-gui/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/git-gui/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/git-gui/lib/git-gui-view.coffee:22:8)
    at Builder.tag (/packages/git-gui/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/git-gui/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.GitGuiView.content (/packages/git-gui/lib/git-gui-view.coffee:20:6)
    at /packages/git-gui/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/git-gui/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/git-gui/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/git-gui/lib/git-gui-view.coffee:12:7)
    at Object.activate (/packages/git-gui/lib/git-gui.coffee:11:23)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  4x -6:52.4.0 core:backspace (input.hidden-input)
     -1:10.1.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:03.5.0 core:confirm (input.hidden-input)
     -0:03.4.0 git-gui:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
git-gui 0.1.27 
platformio-ide-terminal 2.5.0 
terminal-panel 1.14.1 
terminal-plus 0.14.5 
```

**Comment by VadimDor** [comment]
Can confirm this on Windows 8.1 x64 only with Atom 1.19.1 and 1.19.2.
With 1.18 all was OK.
git-gui@0.1.27
Disabling git-gui helps to start Atom.
Crash reports attached
[Atom Crashes.zip](https://github.com/andrewrynhard/atom-git-gui/files/1235557/Atom.Crashes.zip)
