### ISSUE TITLE
Doesn't even install

### ISSUE THREAD

**Issue by darkhog** [andrewrynhard/atom-git-gui#15]
As for now, it fails to even install in Atom.

**Comment by bmaximilian** [comment]
Same Problem here. Output after apm install git-gui:
fsevents@1.1.3 install /private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/fsevents
> node install

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> nodegit@0.16.0 install /private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi
└── (empty)


node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-electron-v1.7-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and electron@1.7.11 (electron-v1.7 ABI, unknown) (falling back to source compile with node-gyp)
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);
           ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
{ Error: Command failed: /private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/openssl/openssl
/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/openssl/openssl' }
/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/openssl/openssl
/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/node_modules/git-gui/node_modules/nodegit/vendor/openssl/openssl' }
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/package.json'
npm WARN apm-install-dir-118314-3042-szsxnu.1mclahsemi No description
npm WARN apm-install-dir-118314-3042-szsxnu.1mclahsemi No repository field.
npm WARN apm-install-dir-118314-3042-szsxnu.1mclahsemi No README data
npm WARN apm-install-dir-118314-3042-szsxnu.1mclahsemi No license field.
npm ERR! Darwin 17.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/max/.atom/.apm/.apmrc" "--userconfig" "/Users/max/.atom/.apmrc" "install" "/private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/d-118314-3042-193jzj8.kvp6s3v7vi/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/lg/0wpd_6l92jx9c14qz2nfr32w0000gn/T/apm-install-dir-118314-3042-szsxnu.1mclahsemi/npm-debug.log
npm ERR! code 1
