### ISSUE TITLE
Download fails for Atom

### ISSUE THREAD

**Issue by albertshort** [andrewrynhard/atom-git-gui#17]
> nodegit@0.16.0 install C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
  Failed to execute 'C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\bin\node.exe C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit\build\Release --dist-url=https://atom.io/download/electron' (1)

npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-electron-v2.0-win32-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and electron@2.0.18 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
gyp

info

it worked if it ends with
ok
gyp
verb cli [ 'C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\bin\\node.exe',
gyp

verb
cli   'C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp
verb
cli
'clean' ]
gyp

info
using
node-gyp@3.4.0
gyp

info
using
node@8.9.3 | win32 | x64
gyp

verb
command
clean []
gyp
verb clean removing "build" directory
gyp

info

ok
gyp

info

it worked if it ends with
ok
gyp
verb cli [ 'C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\bin\\node.exe',
gyp

verb cli
'C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp

verb

cli
'configure',
gyp

verb

cli
'--fallback-to-build',
gyp

verb

cli
'--module=C:\\Users\\<#user#>\\AppData\\Local\\Temp\\apm-install-dir-119421-22864-kylzw1.spbv9\\node_modules\\git-gui\\node_modules\\nodegit\\build\\Release\\nodegit.node',
gyp

verb

cli   '--module_name=nodegit',
gyp
verb cli
'--module_path=C:\\Users\\<#user#>\\AppData\\Local\\Temp\\apm-install-dir-119421-22864-kylzw1.spbv9\\node_modules\\git-gui\\node_modules\\nodegit\\build\\Release',
gyp
verb
cli   '--dist-url=https://atom.io/download/electron' ]
gyp
info using
node-gyp@3.4.0
gyp
info
using
node@8.9.3 | win32 | x64
gyp
verb command configure []
gyp

verb
check python checking for Python executable "python2" in the PATH
gyp

verb `which` failed
Error: not found: python2
gyp

verb
`which` failed
at getNotFoundError (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb
`which` failed     at F (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb
`which` failed     at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:89:16
gyp
verb `which` failed     at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\isexe\index.js:42:5
gyp
verb `which` failed
at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb
`which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp
verb

`which` failed  python2 { Error: not found: python2
gyp
verb `which` failed
at getNotFoundError (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb
`which` failed     at F (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb
`which` failed     at E (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:80:29)
gyp
verb
`which` failed
at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp

verb

`which` succeeded
python C:\Python36-32\python.EXE
gyp
verb check python version `C:\Python36-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.5\r\n"
gyp
ERR! configure error
gyp
ERR! stack Error: Python executable "C:\Python36-32\python.EXE" is v3.6.5, which is not supported by gyp.
gyp ERR!
stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR!
stack     at failPythonVersion (C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack
at C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp
ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack
at ChildProcess.emit (events.js:214:7)
gyp ERR! stack
at maybeClose (internal/child_process.js:925:16)
gyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp
ERR! System Windows_NT 10.0.17763
gyp ERR! command
"C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\<#user#>\\AppData\\Local\\Temp\\apm-install-dir-119421-22864-kylzw1.spbv9\\node_modules\\git-gui\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\<#user#>\\AppData\\Local\\Temp\\apm-install-dir-119421-22864-kylzw1.spbv9\\node_modules\\git-gui\\node_modules\\nodegit\\build\\Release" "--dist-url=https://atom.io/download/electron"
gyp ERR!
cwd C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit
gyp
ERR! node -v v8.9.3
gyp ERR!
node-gyp -v v3.4.0
gyp
ERR! not ok
node-pre-gyp

ERR!

build error

node-pre-gyp

ERR!

stack
Error: Failed to execute 'C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\bin\node.exe C:\Users\<#user#>\AppData\Local\atom\app-1.37.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit\build\Release --dist-url=https://atom.io/download/electron' (1)
node-pre-gyp

ERR!
stack     at ChildProcess.<anonymous> (C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp
ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp

ERR!

stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp
ERR!
stack
at maybeClose (internal/child_process.js:925:16)
node-pre-gyp

ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp

ERR!
System
Windows_NT 10.0.17763
node-pre-gyp
ERR!

command "C:\\Users\\<#user#>\\AppData\\Local\\atom\\app-1.37.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<#user#>\\AppData\\Local\\Temp\\apm-install-dir-119421-22864-kylzw1.spbv9\\node_modules\\git-gui\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp

ERR!
cwd
C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\node_modules\git-gui\node_modules\nodegit
node-pre-gyp

ERR!
node -v
v8.9.3
node-pre-gyp
ERR!

node-pre-gyp -v
v0.6.39
node-pre-gyp

ERR!
not ok

[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\<#user#>\AppData\Local\Temp\apm-install-dir-119421-22864-kylzw1.spbv9\package.json'
npm WARN apm-install-dir-119421-22864-kylzw1.spbv9 No description
npm WARN apm-install-dir-119421-22864-kylzw1.spbv9 No repository field.
npm WARN apm-install-dir-119421-22864-kylzw1.spbv9 No README data
npm WARN apm-install-dir-119421-22864-kylzw1.spbv9 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\git-gui\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<#user#>\.atom\.apm\_logs\2019-05-21T15_52_25_632Z-debug.log

**Comment by AJJLagerweij** [comment]
Same error here
