### ISSUE TITLE
Error trying to toggle git-gui.

### ISSUE THREAD

**Issue by konstantin-popov** [andrewrynhard/atom-git-gui#7]
[Enter steps to reproduce below:]

1. Try to toggle the git-gui panel.

**Atom Version**: 1.12.1
**Electron Version**: 1.3.6
**System**: Windows 7x64
**Thrown From**: [git-gui](https://github.com/andrewrynhard/atom-git-gui) package, v0.1.25

### Stack Trace

Failed to activate the git-gui package

```
At The specified procedure could not be found.
\\?\C:\Users\Konstantin\.atom\packages\git-gui\node_modules\nodegit\build\Release\nodegit.node

Error: The specified procedure could not be found.
\\?\C:\Users\Konstantin\.atom\packages\git-gui\node_modules\nodegit\build\Release\nodegit.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Konstantin\.atom\packages\git-gui\node_modules\nodegit\dist\nodegit.js:11:12)
    at Module._compile (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Konstantin/.atom/packages/git-gui/lib/git-gui-action-bar-view.coffee:1:7)
    at Object.<anonymous> (file:///C:/Users/Konstantin/.atom/packages/git-gui/lib/git-gui-action-bar-view.coffee:1:1)
    at Module._compile (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Konstantin/.atom/packages/git-gui/lib/git-gui-view.coffee:5:23)
    at Object.<anonymous> (file:///C:/Users/Konstantin/.atom/packages/git-gui/lib/git-gui-view.coffee:1:1)
    at Module._compile (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Konstantin/.atom/packages/git-gui/lib/git-gui.coffee:1:14)
    at Object.<anonymous> (file:///C:/Users/Konstantin/.atom/packages/git-gui/lib/git-gui.coffee:1:1)
    at Module._compile (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package.js:741:27)
    at Package.module.exports.Package.activateNow (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package.js:174:16)
    at C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package.js:821:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\command-registry.js:240:20)
    at C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\Konstantin\AppData\Local\atom\app-1.12.1\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
     -0:07.5.0 git-gui:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "django-templates",
      "react",
      "language-babel"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0 (active)
atom-macros, v0.5.2 (active)
django-templates, v0.5.0 (inactive)
file-icons, v1.7.24 (active)
git-control, v0.8.2 (inactive)
git-gui, v0.1.25 (inactive)
git-plus, v5.25.1 (active)
hex, v0.6.2 (active)
Hydrogen, v0.15.0 (inactive)
language-babel, v2.48.1 (inactive)
language-diff, v0.6.0 (active)
language-htaccess, v0.1.1 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-php, v1.3.1 (active)
linter-scss-lint, v3.0.4 (active)
minimap, v4.25.6 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-git-diff, v4.3.1 (active)
php-debug, v0.2.3 (active)
react, v0.16.1 (inactive)
Stylus, v3.1.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by andrewrynhard** [comment]
@konstantin-popov: there was an issue with the version of Nodegit being used. See #6.
